### ISSUE TITLE
Run without animation

### ISSUE THREAD

**Issue by amos80m** [bgryszko/react-native-circular-progress#42]
Hi,
i need the "circular-progress" to run only once, when the app started.
so first page view will do animation and in the next time i am coming back to this page, not to run the animation once again.

**Comment by bgryszko** [comment]
I'm not sure if you've found solution for this. But if not, here is how you can achieve that. I assume you're mounting/unmounting the component and that's why it's reloading the animation. You could use `prefill` prop – it's taken as value of initial state (0 if not passed). So when you want circle filled up to 95% for example and don't perform animation, you should set `prefill` and `fill` to 95.

**Comment by ShaikhKabeer** [comment]
Any sample code is there for running without animation?
