### ISSUE TITLE
Is there a way to add a gradient to a progress line?

### ISSUE THREAD

**Issue by dongweb** [bgryszko/react-native-circular-progress#68]
hi，is there a way to add a gradient to a progress line?

**Comment by vagnerSl** [comment]
+1

**Comment by Jacse** [comment]
I'm afraid it isn't really feasible with the current implementation since SVG does not support conical gradients. The only way to simulate this, that I know of, is to divide the circle into smaller segments each with a different linear gradient.

If you really want this I suggest you take a look at [this](https://stackoverflow.com/questions/18206361/svg-multiple-color-on-circle-stroke) SO question.

**Comment by Jacse** [comment]
Duplicate of #41. It seems doing what I mentioned does result in FPS dropping, so stille a little reluctant to implement.
